### ISSUE TITLE
size of images for validation

### ISSUE THREAD

**Issue by PruneTruong** [juhongm999/dhpf#1]
Hi, I just checked the validation code. It seems that you always resize the images and ground-truth keypoints to 240? So the PCK computation is not computed at original image resolution? 
Thanks

**Comment by juhongm999** [comment]
Yes, images are resized to 240x240 so are the keypoitns and bounding boxes and the PCKs are computed using the resized image and bounding box sizes.
The difference between PCK results of resized and those of original threshold should be negligible.

**Comment by PruneTruong** [comment]
Hi, thanks for the answer! 
I was running your code for evaluation and I do not obtain the same results as the ones you state. Specifically, on PF-Pascal for res101 and weakly supervised  I get 81.87 when mu=0.5 and 80.53 for mu=0.6 whereas you write 82.1 and  80.1 respectively.  I am running with torch 1.0.0 and cuda 10.1 and I also checked with torch 1.7, i obtain the same results.

**Comment by juhongm999** [comment]
I believe there can be some randomness in backbone network initialization in pytorch. Have you tried using torch 1.0.1?

**Comment by PruneTruong** [comment]
Hi, i also tried with pytorch 1.0.1 and i get the same results!

**Comment by juhongm999** [comment]
Interesting. I just ran testing and got 82.13 PCK with mu=0.5 (weakly supervised)

![image](https://user-images.githubusercontent.com/41140817/133321908-3b5b7638-c2c9-4dea-8734-2e50207e48ba.png)

and got 80.12 with mu=0.6 (weakly supervised).

![image](https://user-images.githubusercontent.com/41140817/133322956-2cc2bb07-a192-4c54-af6f-ec1f6dfc1062.png)

Here I share the conda packages I used for above experiments.

![image](https://user-images.githubusercontent.com/41140817/133323168-49084298-0add-4291-81cc-f307db2fdfb6.png)

**Comment by juhongm999** [comment]
Is my experimental setup shown in the above image the same as yours?

**Comment by PruneTruong** [comment]
I use the same pytorch and torchvision as you. 
![Screenshot from 2021-09-14 21-43-34](https://user-images.githubusercontent.com/38944935/133323934-0736f51a-d7fb-411b-81dd-7838ef90ccbd.png)

**Comment by juhongm999** [comment]
I switched the machine (from machine with Titan XP to onew with Titan RTX) to see if it's the machine that causes the issue, and even reinstalled all the required packages as well as backbone parameters as seen below. It's weird I still get the same results and yours are different.

![image](https://user-images.githubusercontent.com/41140817/133327999-2f77023a-73f8-4a37-9cbb-737f713e0781.png)

Have you committed any revisions to our original code?
If not, can you tell us the results after removing PF-PASCAL dataset in ../Datasets_DHPF and redownloading it?

**Comment by PruneTruong** [comment]
I also recloned your repo and ran the test.py, i get exactly the same results than previously. I also removed the dataset and downloaded it again, it didnt change. My results are not very different from yours, but it is still a bit strange

**Comment by juhongm999** [comment]
Hmm.. Maybe try reproducing on different machine?
Are the results still the same?

**Comment by juhongm999** [comment]
Also, is it only the weakly-supervised model causing the issue?
Are you able to reproduce strongly-supervised models?
