### ISSUE TITLE
Error in PCK thresh for PF-Willow

### ISSUE THREAD

**Issue by PruneTruong** [juhongm999/dhpf#3]
Hi, I think you have an error in the PCK-threshold of PF-Willow. 
It is computed as the difference between the maximum and minimum kp. However, since you always pad the kp with -1, the minimum is always -1, which is not the actual coordinate of the minimum keypoint. Therefore, the pckthreshold is artificially large and therefore the results artificially high. 

Once this is corrected, by doing return max(batch['trg_kps'][:, :batch['n_pts']].max(1)[0] - batch['trg_kps'][:, :batch['n_pts']].min(1)[0]).clone()  in return_pck instead, I get around 70 % for alpha=0.1 instead of the 80% you put in the paper.

**Comment by juhongm999** [comment]
Hi, we've corrected this in our recent paper ([link](https://arxiv.org/abs/2109.05221)) as soon as we found that our evaluation scheme on PF-WILLOW is wrong when compared to some recent methods. When doing this research DHPF, we followed the evaluation scheme of some work (I guess it was either SCNet or UCN), but recently found out that the evaluation scheme on PF-WILLOW was diverging. For details, please refer Table 1 and Section 5.1 of our paper ([link](https://arxiv.org/abs/2109.05221)).
We will also correct the code as soon as possible.

**Comment by juhongm999** [comment]
Also, just for your information, there is another issue regarding PF-PASCAL dataset which recent papers frequently discuss; approximately 1/3 of the training pairs overlap with testing pairs. For details, please refer Table 2 of our paper.

**Comment by PruneTruong** [comment]
I see, thanks for the info! Could you share the updated csv files for the training,validatiion split on PF-Pascal?

**Comment by juhongm999** [comment]
Instead making external csv, we manually excluded the overlapping pairs online in our code. We are planning to release the code as soon as possible in this [repo](https://github.com/juhongm999/chm).

[This paper](https://github.com/ActiveVisionLab/ANCNet) also performed unbiased evaluation on PF-PASCAL, and the authors might have csv files with them.
